# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 23:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('star_rating', models.IntegerField()),
                ('review_body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('genre', models.CharField(max_length=30)),
                ('star_rating', models.FloatField()),
                ('like_ration', models.IntegerField()),
                ('blurb', models.CharField(max_length=200)),
                ('starring', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='')),
                ('platform', models.CharField(max_length=30)),
                ('views_total', models.IntegerField()),
                ('ep_runtime', models.IntegerField()),
                ('num_episodes', models.IntegerField()),
                ('num_season', models.IntegerField()),
                ('year_released', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viewership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgement', models.BooleanField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingeworthy.Show')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingeworthy.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='VotesOnReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgement', models.BooleanField()),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingeworthy.Review')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingeworthy.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='viewers',
            field=models.ManyToManyField(through='bingeworthy.Viewership', to='bingeworthy.UserAccount'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_user', to='bingeworthy.UserAccount'),
        ),
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingeworthy.Show'),
        ),
        migrations.AddField(
            model_name='review',
            name='votes',
            field=models.ManyToManyField(related_name='voter_user', through='bingeworthy.VotesOnReview', to='bingeworthy.UserAccount'),
        ),
    ]
