# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingeworthy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='like_ration',
            new_name='like_ratio',
        ),
        migrations.RemoveField(
            model_name='show',
            name='views_total',
        ),
    ]
