# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 16:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeworthy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='like_ration',
        ),
        migrations.RemoveField(
            model_name='show',
            name='star_rating',
        ),
        migrations.RemoveField(
            model_name='show',
            name='views_total',
        ),
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(default='theofficeus1', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='star_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='show',
            name='ep_runtime',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='show',
            name='num_episodes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='show',
            name='num_season',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='show',
            name='picture',
            field=models.ImageField(blank=True, upload_to='show_images'),
        ),
    ]
