# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 00:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingeworthy', '0003_auto_20190318_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='votes',
            field=models.ManyToManyField(related_name='voter_user', through='bingeworthy.VotesOnReview', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='show',
            name='viewers',
            field=models.ManyToManyField(through='bingeworthy.Viewership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewership',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votesonreview',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
