# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 22:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeworthy', '0003_auto_20190305_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='like_ratio',
        ),
        migrations.RemoveField(
            model_name='show',
            name='star_rating',
        ),
        migrations.AlterField(
            model_name='show',
            name='ep_runtime',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='show',
            name='num_episodes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='show',
            name='num_season',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
