# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingeworthy', '0004_auto_20190305_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(default='theofficeus', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='picture',
            field=models.ImageField(blank=True, upload_to='show_images'),
        ),
    ]
