# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 16:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingeworthy', '0005_auto_20190319_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingeworthy.Genre'),
        ),
        migrations.AlterField(
            model_name='show',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bingeworthy.Platform'),
        ),
        migrations.AlterField(
            model_name='viewership',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bingeworthy.Show'),
        ),
        migrations.AlterField(
            model_name='viewership',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votesonreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bingeworthy.Review'),
        ),
        migrations.AlterField(
            model_name='votesonreview',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
