# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingeworthy', '0006_auto_20190319_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewership',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingeworthy.Show'),
        ),
        migrations.AlterField(
            model_name='viewership',
            name='viewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votesonreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingeworthy.Review'),
        ),
        migrations.AlterField(
            model_name='votesonreview',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
