# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingeworthy', '0007_auto_20190320_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpicture',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPicture',
        ),
    ]
